GET http://localhost:3000/api/maps

###

POST http://localhost:3000/api/maps
Content-Type: application/json

{
  "name": "Human Rights",
  "featureCollection": {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "properties": {
          "name": "Universal Declaration of Human Rights",
          "edtf": "1948-12-10"
        },
        "geometry": {
          "type": "Point",
          "coordinates": [2.2877493632177712, 48.86275789409636]
        }
      }
    ]
  }
}
